SPLASHES = [
    "Луна не является планетой",
    "MCPE = MCPi",
    "Ayy Yep!",
    "Какова моя цель?",
    "MCPI_SPEEDHACK",
    "MCPIL-Revival",
    "Minescripters",
    "Я использую Mine BTW",
    "Снежный ком",
    "Robo",
    "Если бы я мог, я бы сделал. Но я не могу, поэтому не буду.",
    "SyntaxError: invalid syntax",
    "Мы починили рельсы!",
    "The World Of Notch!",
    "github.com/PythonScratcher/MineLauncher!",
    "Теперь с флай-хаками!",
    "Теперь с пользовательскими скинами!",
    "Теперь с *модными иконками*!",
    "@Banana",
    "BANANA!",
    'To "Na" Or Not To "Na", вот в чем вопрос!',
    "Не Minecraft Java!",
    "Ах да, эта версия...",
    "Segmentation fault (core dumped)",
    "Это ошибка сегментации!",
    "Кто такой СтивПи?",
    "(Not) Made by Notch!",
    "Open-Source!",
    "RIP all MCPILs, 2020-2022",
    "StevePi = Beiop подтвержден?",
    "Осторожно, СтивПи!",
    "Не удалил Херобрина!",
    "Проверьте анархию PBPT!",
    "你好中国",
    "한국 안녕하세요!",
    "日本ハロー！",
    "Привет Россия!",
    "Підтримай Україну!",
    "Supercalifragilisticexpialidocious!",
    "Теперь с мультиплеером!",
    "КРАСНЫЙ ИНЖЕНЕРНЫЙ ГЕЙМИНГ",
    "Играй в Minecraft Pi Edition, смотри Red-Exe-Engineer, получай PIG!",
    "Вт",
    "Подписаться на PythonScratcher!",
]
#Переведено с помощью www.DeepL.com/Translator (бесплатная версия)

